# required vars:
# - uid
# - entity_id

sensor:
  # Aktuelle Temperatur (Ist-Wert)
  - platform: homeassistant
    id: ${uid}_current_temp
    entity_id: ${entity_id}
    attribute: current_temperature
    on_value:
      - lvgl.label.update:
          id: ${uid}_widget_current
          text:  #!lambda 'return String(x) + "째C";'
            format: "%.1f 째C"
            args: [x]

  # Soll-Temperatur (Zielwert)
  - platform: homeassistant
    id: ${uid}_target_temp
    entity_id: ${entity_id}
    attribute: temperature
    on_value:
      - lvgl.label.update:
          id: ${uid}_widget_target
          text: #Test #!lambda 'return String(x) + "째C";'
            format: "%.1f 째C"
            args: [x] 
      - lvgl.slider.update:
          id: ${uid}_widget_slider
          value: !lambda 'return x;'

